### ISSUE TITLE
Support Biometric Prompt API (Google Pixel 4 Face Unlock)

### ISSUE THREAD

**Issue by phillbaker** [hieuvp/react-native-fingerprint-scanner#110]
In order to support Google Pixel's new Face Unlock functionality, the new [BiometricPrompt](https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt) API would need to be supported.

It looks like this library may be used: https://mvnrepository.com/artifact/androidx.biometric/biometric. More information:
* https://android-developers.googleblog.com/2019/10/one-biometric-api-over-all-android.html
* https://medium.com/mindorks/fingerprint-authentication-using-biometricprompt-compat-1466365b4795
* https://developer.android.com/reference/androidx/biometric/package-summary

This is separate from https://github.com/hieuvp/react-native-fingerprint-scanner/issues/80 in which the Galaxy 10 is currently supported.

**Comment by chris-griffin** [comment]
Here is a relevant similar PR in another package: https://github.com/SelfLender/react-native-biometrics/pull/54/files#

This troubleshooting tip seems like it will be relevant as well

[>  Because of this library's dependency on androidx.biometric:biometric:1.0.0 it can cause transitive dependency resolution to change on certain version of React Native and androidx.swiperefreshlayout may no longer be able to be resolved. This can be fixed by adding an explicit dependency on the library in your android/app/build.gradle:
> 
> dependencies {
>     implementation fileTree(dir: "libs", include: ["*.jar"])
>     implementation "com.facebook.react:react-native:+"  // From node_modules
>     implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0" // temp fix
>     ...
> }](https://github.com/SelfLender/react-native-biometrics/blob/92861b93005ffe798c61f2c2f20fa68b4c0f749c/README.md#troubleshooting)

**Comment by fkotsian** [comment]
Closed via #115
