### ISSUE TITLE
Can we use the fingerprint to verify with third part  API?

### ISSUE THREAD

**Issue by ali-chaudhry** [hieuvp/react-native-fingerprint-scanner#138]
I am building an application where we will confirm the authenticity of use via fingerprint with our record of fingerprints. Can we perform that while using this package?

**Comment by mikehardy** [comment]
Unless I read all the documentation wrong, the actual biometric information (the real fingerprint) is one-way stored on the device, and all we are doing is asking the hardware to compare, we have no access whatsoever to the biometric data, only comparison results.

If I'm wrong, I'd love to know because we potentially have this use case as well but I'm not aware of a way to satisfy it

**Comment by phillbaker** [comment]
I believe this is similar to https://github.com/hieuvp/react-native-fingerprint-scanner/issues/54 can you take a look at that discussion and see if it answers the question?
