### ISSUE TITLE
Saving Fingerprint data into a database

### ISSUE THREAD

**Issue by cardyy** [hieuvp/react-native-fingerprint-scanner#174]
I have been going through the library and saw that it mainly authenticates fingerprints, i wanted to ask if there can be a way to save the fingerprint data into a database through a post request maybe . How can i capture the fingerprint information

**Comment by mikehardy** [comment]
Hi there! You should examine how the authentication and biometrics work on the platform. When I checked (since I was curious if it was possible to do something similar) it seemed to me that the *platform* (as in: the operating system, nothing available via APIs) captured the biometric data and stored it within the platform. The only thing information that is exposed via APIs that this module (or any app can use) are APIs that are effectively "hey Platform, can you request biometric auth from the user?" to which the platform replies with a successful authentication or not.

No biometric data is available to the app at any time as far as I saw

**Comment by 276259822** [comment]
[evaluatedPolicyDomainState](https://developer.apple.com/documentation/localauthentication/lacontext/1514150-evaluatedpolicydomainstate)
```node_modules/react-native-fingerprint-scanner/ios/ReactNativeFingerprintScanner.m```

```
if (success) {
                 // Authenticated Successfully
                 if (context.evaluatedPolicyDomainState) {
                   NSString *biometryData = [context.evaluatedPolicyDomainState base64EncodedStringWithOptions:NSDataBase64Encoding64CharacterLineLength];
                   callback(@[[NSNull null], biometryData]);
                   return;
                 } else {
                   callback(@[[NSNull null]]);
                   return;
                 }
             }
```

**Comment by mikehardy** [comment]
@276259822 that is cool and I did not even know that was possible, however, it does not actually return the biometrics, which was the question. That said it does at least offer comparison, which is ...maybe interesting. I'm going to close this as a combo of "not really possible" along with "but looks like code above can get you there". I left notes on #163 proposing how to get it integrated if someone wants to propose a PR
