### ISSUE TITLE
Fallback option not appearing in iOS simulator running iOS 11

### ISSUE THREAD

**Issue by sahil290791** [hieuvp/react-native-fingerprint-scanner#21]
This library is cool but I am not getting fallback option where a user could enter password.

Here is my code: 
```
FingerprintScanner
        .authenticate({
          onAttempt: this.handleAuthenticationAttempted,
          description: 'Scan your fingerprint on the device scanner to continue',
          fallbackEnabled: true,
        })
        .then(() => {
          this.fingerprintSuccess();
        })
        .catch((error) => {
          this.setState({ error });
          if (Platform.OS === 'ios' && !isUndefined(error) && error.name === 'AuthenticationFailed') {
            AlertIOS.alert('Touch ID for example', error.message, [
              {
                text: 'Ok',
                onPress: () => this.enableFingerprintScanner(this.props),
              },
            ]);
          }
        });
```

### Additional Details:
- RN: 0.42.3
- react-native-fingerprint-scanner: 2.2.1

**Comment by phillbaker** [comment]
@sahil290791 what version of the XCode are you running? Looks like there was a bug in the simulator with [Touch ID in XCode 9 Beta 4](https://stackoverflow.com/a/45288796).

**Comment by phillbaker** [comment]
Closing for now as there's been no follow up. @sahil290791  please re-open if there are more details!

**Comment by gopikasireddy202** [comment]
Hi Team,

In iOS when user authentication is failed then user is enter password in the pop up.When i click on enter password on pop up it shows a message like Authentication was cancelled because the user tapped the fallback button(Enter Password).
I need to navigate to Passcode screen when user tapped on the enter password popup if the user authentication is failed.

Can you please give the code for below method.

this.enableFingerprintScanner(this.props)

Thank you.
