### ISSUE TITLE
Confused by this commit

### ISSUE THREAD

**Issue by mobitar** [hieuvp/react-native-fingerprint-scanner#32]
In 747c049a8977b9f5a81319426165dd2627618649, the ` if (mFingerprintIdentify == null)` check is removed, so every call to `getFingerprintIdentify()` results in the creation of a new `FingerprintIdentify` object. 

In `getErrorMessage()`, this can be called 3 times, meaning 3 objects are created and also duplicate calls to `mReactContext.addLifecycleEventListener(this);`

Are we sure this is safe to do?

**Comment by aadishah** [comment]
Hi, 
I have been working on this bug. I have faced no issues with all devices except Google Pixel and Nexus devices. 

On Nexus 6p and Pixel 2, The duplicate calls which you're talking about cause the `onFailed()` function to be called as soon as the app starts, so when the user hits the button for touch authentication popup to show up, the application shows the popup with the error: `AuthenticationFailed: 'Authentication was not successful because the user failed to provide valid credentials.'`.

So I would suggest we revert my changes in 
[747c049](
https://github.com/hieuvp/react-native-fingerprint-scanner/commit/747c049a8977b9f5a81319426165dd2627618649)

I will then open up an issue for the problem i was facing which is: User deletes fingerprints on device and then re-add's them, the app still says that there are no fingerprints on device. We could find another fix for this issue. 

Thank You for bringing it up.

**Comment by mobitar** [comment]
> User deletes fingerprints on device and then re-add's them, the app still says that there are no fingerprints on device. We could find another fix for this issue.

I tested this myself on a huawei honor 6 but could not replicate this issue. Deleting a fingerprint then re-adding it works works as expected.

**Comment by ValentinBlokhin** [comment]
@aadishah any progress on this? We really need it.

**Comment by ESA2012** [comment]
Redundant creation of new instances causes `'Authentication was not successful because the user failed to provide valid credentials.'` error
