### ISSUE TITLE
Is it supports for android version 8.1

### ISSUE THREAD

**Issue by RavindraMaddukuri** [hieuvp/react-native-fingerprint-scanner#81]
Hi everyone,
     I have little confusion that react-native-fingerprint-scanner the latest version of Android.

**Comment by cinder92** [comment]
same here, is working, but not appearing the finger print scanner

**Comment by phillbaker** [comment]
Can you share any errors you're seeing?

**Comment by phillbaker** [comment]
Going to close for now as no error outputs or stacktraces have been included. We've had success using this library in the emulator on android 9.0 and have usages of this on real devices with 8.0, 8.1 and 9.0.

**Comment by jenskuhrjorgensen** [comment]
Hi @phillbaker 
I ended here because of your README phrase: 

> Samsung and MeiZu's Fingerprint SDK supports most devices which system versions less than Android 6.0.

Does this mean that you don't support Android versions newer/higher than 6.0? Your previous comment on this issue indicates otherwise.

**Comment by phillbaker** [comment]
@jenskuhrjorgensen all Android versions are supported!

Google has slowly been adding better support for fingerprint/biometric (see https://github.com/hieuvp/react-native-fingerprint-scanner/issues/110) both in Android itself and as officially supported APIs. However, older androids did rely much more on these external libraries, which is why it's called out.
