### ISSUE TITLE
I'm getting an error FingerprintScannerNotEnrolled.

### ISSUE THREAD

**Issue by chapeljuice** [hieuvp/react-native-fingerprint-scanner#9]
Complete error says:
`07-21 11:23:06.433  4639  5443 I ReactNativeJS: { [FingerprintScannerNotEnrolled: Authentication could not start because Fingerprint Scanner has no enrolled fingers.] name: 'FingerprintScannerNotEnrolled' }`

What does this mean?

Some details about my environment:
`"react": "^16.0.0-alpha.6",`
`"react-native": "^0.44.0",`
`"react-native-fingerprint-scanner": "^2.1.3",`

My code:
```  import FingerprintScanner from 'react-native-fingerprint-scanner'

  componentDidMount() {
    if (Platform.OS === 'ios') {
      console.log('ios device, trying to use fingerprint scanner')
      // iOS code only
      FingerprintScanner
        .authenticate({ description: 'Scan your fingerprint on the device scanner to continue' })
        .then(() => {
          AlertIOS.alert('Authenticated successfully')
        })
        .catch((error) => {
          console.log(error)
        })
    } else if (Platform.OS === 'android') {
      console.log('android device, trying to use fingerprint scanner')
      // android code only
      FingerprintScanner
        .authenticate({ onAttempt: this.handleAuthenticationAttempted })
        .then(() => {
          Alert.alert('Fingerprint Authentication', 'Authenticated successfully')
        })
        .catch((error) => {
          console.log(error)
        })
    }
  }

  componentWillUnmount() {
    if (Platform.OS === 'android') {
      FingerprintScanner.release()
    }
  }

**Comment by foxmicha** [comment]
This error means exactly as it says: There are no fingerprints currently enrolled in the OS. 

For iOS simulators, you just need to go to Hardware -> TouchID -> Toggle TouchID Enrollment Status in order to turn it on. 

For Android Emulators you'll have to actually go through the process of enrolling one of the 10 fingerprints that are included in the kabob context menu (last button in the list that stays next to the Emulator when you launch it).

**Comment by phillbaker** [comment]
@chapeljuice any follow up here? Otherwise it looks like this issue can be closed.
